/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.AbsoluteDistanceMetric;
import Model.ComplexFeature;
import Model.DistanceMetric;
import Model.EuclideanDistanceMetric;
import Model.PolarCoordinateDistanceMetric;
import Model.SimpleFeature;

/**
*
* @author jobin, Eric
*/
public class ComplexFeatureGUI extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ComplexFeature feature;
	private int tracker;
	private DistanceMetric distanceMetric;
   /**
    * Creates new form NewJFrame2
    */
   public ComplexFeatureGUI(int value, ComplexFeature feature) {
   	tracker = value;
   	this.feature = feature;
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       ComplexFeatureDialog = new javax.swing.JDialog();
       valueLabel = new javax.swing.JLabel();
       nameLabel = new javax.swing.JLabel();
       valueInputLabel = new javax.swing.JLabel();
       nameTextField = new javax.swing.JTextField();
       valueTextField = new javax.swing.JTextField();
       complexValueRadioButton = new javax.swing.JRadioButton();
       addAnotherButton = new javax.swing.JButton();
       finishButton = new javax.swing.JButton();
       distanceMetricComboBox = new javax.swing.JComboBox<>();
       distanceMetricLabel = new javax.swing.JLabel();
       jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

       ComplexFeatureDialog.setPreferredSize(new java.awt.Dimension(400, 250));
       ComplexFeatureDialog.setResizable(false);

       valueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       valueLabel.setText("Value " + Integer.toString(tracker));

       nameLabel.setText("Name: ");

       valueInputLabel.setText("Value: ");

       complexValueRadioButton.setText("Complex Value");
       complexValueRadioButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               complexValueRadioButtonActionPerformed(evt);
           }
       });

       addAnotherButton.setText("Add Another Feature");
       addAnotherButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               addAnotherButtonActionPerformed(evt);
           }
       });

       finishButton.setText("Finish");
       finishButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               finishButtonActionPerformed(evt);
           }
       });
       
       String[] distanceMetrics = {"Absolute", "Euclidean","Polar"};
       distanceMetricComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(distanceMetrics));
       distanceMetricComboBox.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               distanceMetricComboBoxActionPerformed(evt);
           }
       });

       distanceMetricLabel.setText("Distance Metric: ");

       javax.swing.GroupLayout ComplexFeatureDialogLayout = new javax.swing.GroupLayout(ComplexFeatureDialog.getContentPane());
       ComplexFeatureDialog.getContentPane().setLayout(ComplexFeatureDialogLayout);
       ComplexFeatureDialogLayout.setHorizontalGroup(
           ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
               .addContainerGap()
               .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
                       .addComponent(distanceMetricLabel)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(distanceMetricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
                       .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(valueInputLabel)
                           .addComponent(nameLabel))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(nameTextField)
                           .addComponent(valueTextField)))
                   .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
                       .addGap(1, 1, 1)
                       .addComponent(complexValueRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
                       .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(0, 0, Short.MAX_VALUE))
                   .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
                       .addComponent(addAnotherButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addContainerGap())
       );
       ComplexFeatureDialogLayout.setVerticalGroup(
           ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(ComplexFeatureDialogLayout.createSequentialGroup()
               .addContainerGap()
               .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(nameLabel)
                   .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(valueInputLabel)
                   .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(complexValueRadioButton)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(distanceMetricComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(distanceMetricLabel))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(ComplexFeatureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(finishButton)
                   .addComponent(addAnotherButton))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );

       jCheckBoxMenuItem1.setSelected(true);
       jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
       );

       ComplexFeatureDialog.pack();
       ComplexFeatureDialog.setLocationRelativeTo(null);
       ComplexFeatureDialog.setVisible(true);
   }// </editor-fold>                        

   private void complexValueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
       valueTextField.setEnabled(!valueTextField.isEnabled());
   }                                                       

   private void distanceMetricComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       
   }                                                      

   private void addAnotherButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
   	createFeature();
		nameTextField.setText("");
		valueTextField.setText("");
		complexValueRadioButton.setSelected(false);
		 valueTextField.setEnabled(true);
		tracker++;
		valueLabel.setText("Value " + Integer.toString(tracker));
   }                                                

   private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
       createFeature();
       ComplexFeatureDialog.dispose();
   }                                            

   private void createFeature() {
	   //Setting the type of distanceMetric
	   String selectedDistanceMetric = distanceMetricComboBox.getSelectedItem().toString();
	   if(selectedDistanceMetric.equals("Absolute")) distanceMetric = new AbsoluteDistanceMetric();
	   else if(selectedDistanceMetric.equals("Euclidean")) distanceMetric = new EuclideanDistanceMetric();
	   else if(selectedDistanceMetric.equals("Polar")) distanceMetric = new PolarCoordinateDistanceMetric();
	   //Add new distanceMetrics here...

	   if(nameTextField.getText().length()>0) {
			if(nameTextField.getText().contains(" ")){
				Popup.infoBox("You cannot have spaces in the Name.", "INPUT ERROR");
			}
			else if(complexValueRadioButton.isSelected()) {
				ComplexFeature f = new ComplexFeature(nameTextField.getText());
				new ComplexFeatureGUI(1,f);
				dispose();
			}
			else {
				SimpleFeature f;
				try {
					int val = Integer.parseInt(valueTextField.getText());
					f = new SimpleFeature(nameTextField.getText(),val,"Num",distanceMetric);
				} catch(NumberFormatException e) {
					f = new SimpleFeature(nameTextField.getText(),valueTextField.getText(),"String",distanceMetric);
				}
				feature.addChildFeature(f);
				dispose();
			}
   	} else {
   		Popup.infoBox("Please Enter a Name and Select a Type.", "INPUT ERROR");
		}
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(ComplexFeatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(ComplexFeatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(ComplexFeatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(ComplexFeatureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
           	ComplexFeature f = new ComplexFeature("test");
               new ComplexFeatureGUI(1,f).ComplexFeatureDialog.setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify                     
   private javax.swing.JDialog ComplexFeatureDialog;
   private javax.swing.JButton addAnotherButton;
   private javax.swing.JRadioButton complexValueRadioButton;
   private javax.swing.JComboBox<String> distanceMetricComboBox;
   private javax.swing.JLabel distanceMetricLabel;
   private javax.swing.JButton finishButton;
   private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
   private javax.swing.JLabel nameLabel;
   private javax.swing.JTextField nameTextField;
   private javax.swing.JLabel valueInputLabel;
   private javax.swing.JLabel valueLabel;
   private javax.swing.JTextField valueTextField;
   // End of variables declaration                   
}
